version: 2.1
jobs:
  grpc_protocol:
    docker:
      - image: externalreality/invoices-build-image
    steps:
      - checkout

      - run:
          name: Build GPRC Protobuf Protocols
          command: cargo build -p grpc_protocol

      - persist_to_workspace:
          root: ./grpc_protocol
          paths:
            - src

  analysis_server:
    docker:
      - image: externalreality/invoices-build-image
    steps:
      - checkout

      - attach_workspace:
          at: ./grpc_protocol

      - run:
          name: Build Analysis Server
          command: cargo build -p analysis_server

workflows:
  version: 2
  build:
    jobs:
      - grpc_protocol
      - analysis_server:
          requires:
            - grpc_protocol