version: 2.1
jobs:
  grpc_protocol:
    docker:
      - image: externalreality/invoices-build-image
    steps:
      - checkout

      - run:
          name: Build GPRC Protobuf Protocols
          command: cargo build -p grpc_protocol

      - persist_to_workspace:
          root: ./grpc_protocol
          paths:
            - src

  analysis_server:
    docker:
      - image: externalreality/invoices-build-image
    steps:
      - checkout

      - attach_workspace:
          at: ./grpc_protocol

      - run:
          name: Build Analysis Server
          command: cargo build -p analysis_server

  invoice_server:
    docker:
      - image: externalreality/invoices-build-image
    steps:
      - build-service:
          display_name: Invoice Server
          package_name: invoice_server

workflows:
  version: 2
  build:
    jobs:
      - grpc_protocol
      - analysis_server:
          requires:
            - grpc_protocol
      - invoice_server:
          requires:
            - grpc_protocol

commands:
  build-service:
    description: "Boilerplate rust service build config"
    parameters:
      display_name:
        type: string
      package_name:
        type: string
    steps:
      - checkout
      - attach_workspace:
          at: ./grpc_protocol
      - run:
          name: Build << parameters.display_name >>
          command: cargo build -p << parameters.package_name >>