company_name = "Company"
email = "email"
phone = "222-2222"
total_price = 154.22
timestamp = "383838383838"

[address]
street = "street"
city = "city"
zip = "zip"

[bill_to]
street = "17 Turk Hill Rd"
city = "brewster"
zip = "10509"



