[package]
name = "invoice_server"
version = "0.1.0"
authors = ["externalreality <ecjones@protonmail.com>"]
edition = "2018"

[dependencies]
uuid = {version = "0.7.4", features = ["v4"]}
grpcio = "0.4.4"
protobuf = "2.6.1"
futures = "0.1.27"

grpc_protocol = { path = "../grpc_protocol" }
